"XXX/XXY" = 1000
"X monosomy" = 3500
pseudo_merle = 200
breakthrough = 50
dense_blotched = 50

# All genes are 1/x chances. They can be set to 0 to prevent it from appearing at all
longhair = 2
longtype = [
    'long',
    'long',
    'long',
    'medium',
] #whether a longhair appears as longhair or as a mediumhair
cinnamon = 35
chocolate = 20
red = 4
dilute = 2
"dominant white" = 40
"white spotting" = 3
"birman gloving" = 50
"thai white" = 400
salmiak = 300
colourpoint = 10
sepia = 20
mocha = 300
albino = 200
silver = 20
solid = 2
charcoal = 150
blotched = 3
ticked = 10

"pink-eyed dilute" = 400
"dilute modifier" = 150
grizzle = 275
carnelian = 200
russet = 250
amber = 125
sunshine = 125
"extreme sunshine" = 125
copper = 125
bleaching = 400
ghosting = 400
satin = 400
glitter = 150

wirehair = 400
laperm = 400
cornish = 200
urals = 400
tenn = 300
fleece = 450
selkirk = 300
devon = 200
"canadian hairless" = 300
"russian hairless" = 400
lykoi = 350

curl = 300
four_ears = 300
manx = 300
"american bobtail" = 300
"karelian bobtail" = 500
"kurilian bobtail" = 400
"japanese bobtail" = 250
toybob = 400
ringtail = 400
munchkin = 300
polydactyl = 150
DBE = 150

body_ranges = [1, 4, 12, 60, 12, 4, 1]
height_ranges = [1, 4, 12, 60, 180, 60, 12, 2, 2, 1]
wideband = ["2", "1", "1", "1", "0"]
rufousing = ["2", "1", "1", "1", "0"]
spotted = ["2", "1", "0"]
tickmod = ["2", "1", "1", "1", "0", "0", "0", "0", "0", "0", "0"]
bengal = ["2", "1", "1", "1", "0", "0", "0", "0", "0", "0", "0"]
sokoke = ["2", "2", "1", "1", "1", "1", "0", "0", "0"]
