name: PyInstaller build

on:
  push:
    paths-ignore:
      - ".github/workflows/build-docs.yml"
      - "docs/**"
      - "docs-resources/**"
      - "mkdocs.yml"
      - "Dockerfile"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            artifact_name: Genemod_Catmaker_Linux64_glibc2.31+.tar.xz
            python_version: "3.11"
            python_arch: "x64"
            itch_channel: linux64_glibc_231
            api_artifact_name: linux2.31

          - os: ubuntu-22.04
            artifact_name: Genemod_Catmaker_Linux64_glibc2.35+.tar.xz
            python_version: "3.11"
            python_arch: "x64"
            itch_channel: linux64_glibc_235
            api_artifact_name: linux2.35

          - os: windows-2019
            artifact_name: Genemod_Catmaker_Win32.zip
            python_version: "3.8"
            python_arch: "x86"
            itch_channel: win32
            api_artifact_name: win32

          - os: windows-latest
            artifact_name: Genemod_Catmaker_Win64.zip
            python_version: "3.8"
            python_arch: "x64"
            itch_channel: win64
            api_artifact_name: win64

          - os: windows-latest
            artifact_name: Genemod_Catmaker_Win64_Windows10+.zip
            python_version: "3.11"
            python_arch: "x64"
            itch_channel: win64_10
            api_artifact_name: win10+

          - os: macos-13
            artifact_name: Genemod_Catmaker_macOS64.dmg
            python_version: "3.11"
            python_arch: "x64"
            itch_channel: osx64
            api_artifact_name: macOS

    runs-on: ${{ matrix.os }}
    if: ${{ !startsWith(github.ref, 'ref/heads/release') }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.1
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          architecture: ${{ matrix.python_arch }}
          cache: "poetry"
      - name: Install build dependencies (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev
      - name: Install build dependencies (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          brew install zlib
      - name: Install Visual Studio Build Tools (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.1
      - name: Set up cargo cache (Windows)
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: install dependencies
        run: poetry install --with build
      - name: Build PyInstaller bootloader
        run: |
          git clone https://github.com/pyinstaller/pyinstaller.git
          cd pyinstaller
          git checkout v6.11.0
          cd bootloader
          python ./waf all
          cd ../../
          poetry run pip install -e pyinstaller
      - name: Run PyInstaller
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: poetry run python -m PyInstaller Catmaker.spec
      - name: Create archive (Linux)
        if: startsWith(matrix.os, 'ubuntu')
        run: tar -caf ${{ matrix.artifact_name }} -C dist Genemod_Catmaker
      - name: Create archive (Windows)
        if: startsWith(matrix.os, 'windows')
        shell: powershell
        run: |
          cp dist/ tar.exe -a -f ${{ matrix.artifact_name }} -C dist Genemod_Catmaker
      - name: Create DMG (macOS)
        if: startsWith(matrix.os, 'macos')
        run: |
          rm -r dist/Genemod_Catmaker
          npm install -g appdmg
          appdmg appdmg.json ${{ matrix.artifact_name }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ${{ matrix.artifact_name }}
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.artifact_name }}

  confirm_release:
    runs-on: ubuntu-22.04
    if: ${{ vars.USE_UPDATE_API != '' && (github.ref == 'refs/heads/development' || startsWith(github.ref, 'refs/tags/')) }}
    needs: build
    steps:
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
